### ISSUE TITLE
How much time do you spend reading the news?

### ISSUE THREAD

**Issue by winkler1** [survivejs/ama#1]
The JS ecosystem is famously a crazy cauldron..  how do you read the tea leaves for what's worth paying attention to?

**Comment by bebraw** [comment]
It's hard to give an exact figure. But I would guess it's at least hours per week. I gain surprisingly much from discussions with other people, including my readers. As an information source that's at least as important as articles if not more. This allows me to keep up with the trends somehow.

I maintain [@jsterlibs](https://twitter.com/jsterlibs) in addition to [@survivejs](https://twitter.com/survivejs). This forces me to spend some time outside of the React world. Often I just skim the articles at my Twitter feeds and read those that look most interesting.

The signal to noise seems lower these days than before. There's a lot more content, but I find a lot of it trivial in one way or another. Fortunately there's still original, and interesting, content around if you dig enough. It's just harder to find. In part this has to do with the fact that given I've been following the scene a long time, beginner level material just doesn't resonate with me anymore. :smile:

For a casual follower, a good strategy might be just to ignore a lot what's going on and do a weekly, or even monthly, check on the scene. Usually it's very hard to miss the most influential ideas. Of course that doesn't mean they are going to stick, but that's JavaScript! A conservative approach like this would at least shield you from abrupt changes. Babel 5 → 6 transition comes to mind. By waiting a bit you let others absorb some of the pain.
