### ISSUE TITLE
How to implement CSS Modules with separate cache-busting chunks?

### ISSUE THREAD

**Issue by ericleite** [survivejs/ama#10]
I've been following the book for my webpack setup, but I've been having trouble implementing CSS Modules (using css-loader) with separate cache-busting chunks. In the book, we setup a specific entry point for the app and for the styles:

``` javascript
  entry: {
    app: path.resolve('./src'),
    style: path.resolve('./src/components/App.css')
  },
```

And we have CSS extraction running on `entry.style`:

``` javascript
exports.extractCSS = function(paths) {
  return {
    module: {
      loaders: [
        // Extract CSS during build
        {
          test: /\.css$/,
          loader: ExtractTextPlugin.extract('style', 'css?modules&importLoaders=1!postcss'),
          include: paths
        }
      ]
    },
    plugins: [
      // Output extracted CSS to a file
      new ExtractTextPlugin('[name].[chunkhash].css')
    ]
  }
}
```

The problem is that with CSS Modules, the idea is to have separate css files for each component and use `var styles = require('./Button.css');` to import it into the JS of the component. That means I need to constantly update `entry.style` with each new css file I add:

``` javascript
  entry: {
    app: path.resolve('./src'),
    style: [
      path.resolve('./src/components/App.css'),
      path.resolve('./src/components/Button/Button.css'),
      path.resolve('./src/components/Input/Input.css'),
      path.resolve('./src/components/AnotherComponent/AnotherComponent.css'),
      ...
    ]
  },
```

Is there a way to just define the top level src/components directory and have webpack find all the CSS files automatically? If I use just `path.resolve('./src/components')`, I get this error:
`ERROR in multi style
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/Eric/Projects/test/app/src/components in /Users/Eric/Projects/test/app
 @ multi style`

Here's the full setup I'm working with - [app.zip](https://github.com/survivejs/ama/files/560238/app.zip)

**Comment by ericleite** [comment]
Another thing I noticed happening was that since I need to require my CSS into my JS to use CSS Modules, the extractBundle function is creating a vendor.[hash].css bundle even though I don't have any vendor css in my project. See the following screenshot:

<img width="615" alt="screen shot 2016-10-29 at 6 21 48 pm" src="https://cloud.githubusercontent.com/assets/10524608/19833805/99edf732-9e04-11e6-97fb-4bf280711b12.png">

**Comment by bebraw** [comment]
Hi,

``` javascript
  entry: {
    app: path.resolve('./src'),
    style: [
      path.resolve('./src/components/App.css'),
      path.resolve('./src/components/Button/Button.css'),
      path.resolve('./src/components/Input/Input.css'),
      path.resolve('./src/components/AnotherComponent/AnotherComponent.css'),
      ...
    ]
  },
```

That `style` portion can be replaced with something like `style: glob.sync('./src/components/**/*.css')`. See [glob](https://www.npmjs.com/package/glob) for more info.

> Another thing I noticed happening was that since I need to require my CSS into my JS to use CSS Modules, the extractBundle function is creating a vendor.[hash].css bundle even though I don't have any vendor css in my project.

Are you going to have vendor dependencies though? I suppose there are two options - either ignore the generated CSS or disable the vendor portion.

Let me know how it goes.

**Comment by ericleite** [comment]
Hey, thanks for the tips! I added glob and it's working well.

For the vendor.css issue, I wanted to point out that it's creating a `vendor.css` instead of `style.css` like it does in the book's setup. It's taking the CSS _I created_ (non-vendor) and throwing it in a file called `vendor.css`. This only started happening after I started using the CSS Modules feature of css-loader and requiring my CSS files inside my JS.

For now, I can just force the name using:

``` javascript
new ExtractTextPlugin('main.[chunkhash].css')
```

Instead of:

``` javascript
new ExtractTextPlugin('[name].[chunkhash].css')
```

But if I did want to include vendor css, would it make sense to run the `extractCSS` function twice - once for my CSS, and once for any vendor CSS (should I need it)? It might look something like this:

``` javascript
exports.extractCSS = function(name, paths) {
  return {
    module: {
      loaders: [
        // Extract CSS during build
        {
          test: /\.css$/,
          loader: ExtractTextPlugin.extract('style', 'css?modules&importLoaders=1!postcss'),
          include: paths
        }
      ]
    },
    plugins: [
      // Output extracted CSS to a file
      new ExtractTextPlugin(name+'.[chunkhash].css')
    ]
  }
}
```

Also, when extracting vendor CSS, I wouldn't want to run it with CSS Modules, so would I need to make the loader variable as well?

**Comment by bebraw** [comment]
> But if I did want to include vendor css, would it make sense to run the extractCSS function twice - once for my CSS, and once for any vendor CSS (should I need it)? It might look something like this:

That sounds reasonable.

> Also, when extracting vendor CSS, I wouldn't want to run it with CSS Modules, so would I need to make the loader variable as well?

I think that would require a separate configuration without CSS Modules enabled, yeah.

I don't mind having a closer look if you can link to a little sample project.

**Comment by ericleite** [comment]
Sounds good, I'll follow up if that doesn't work out.
