### ISSUE TITLE
React.createElement in 'react-and-flux' chapter

### ISSUE THREAD

**Issue by Axolot1** [survivejs/ama#12]
hi, thanks for the great react book. In `app/libs/connect.jsx`
I have a problem when try to replace
``` 
return React.createElement(target,
        {...Object.assign(
          {}, this.props, state(composedStores), actions
        )}
      );
```
with
```
return (<target {...Object.assign(
          {}, this.props, state(composedStores), actions
        )}/>);
```
i got an error: `Warning: Unknown props `flux`, `test` on <target> tag.`.  I can't figure out what's wrong in my code.

**Comment by bebraw** [comment]
Hi,

Can you push your project somewhere? It's easier to tell what's going on then.

I would probably write

```javascript
return React.createElement(
  target,
  Object.assign({}, this.props, state(composedStores), actions)
);
```

now.

**Comment by Axolot1** [comment]
The `React.createElement`work fine and no waring, i think it's the same to write in JSX, but i keep getting this warning and the app won't show up.

**Comment by Axolot1** [comment]
```
Warning: Unknown props `flux`, `test` on <target> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in target (created by Connect)
    in Connect
    in AltContainer (created by Unknown)
    in Unknown
```
The codebase is the same as the react book.

**Comment by bebraw** [comment]
Alright. Basically the warning is saying you are passing props it does not expect to receive. That `test` might be something you pass, but that `flux` is something we could destructure or omit.

You could do an intermediate step like this:

```javascript
const { flux, ...props } = { ...this.props, ...state(composedStores), ...actions };

return <target {...props } />;
```

**Comment by Axolot1** [comment]
The chapter http://survivejs.com/react/implementing-kanban/react-and-flux/ .
I use the code you post and got  a bunch of error, may be i should push the project. I am just curious  
that the book use JSX except the `app/libs/connect.jsx` use `create element`, and according the https://facebook.github.io/react/docs/react-without-jsx.html , it's the same, i just wonder there is a reason we should use `createElement` here? Sorry for my poor english, I hope i make myself clear.

**Comment by bebraw** [comment]
Ah, I see now. Consider

```jsx
const Target = 'a';
const a = <Target className="foo" />;

const target = 'a';
const b = <target className="foo" />;
```

This compiles to

```javascript
'use strict';

var Target = 'a';
var a = React.createElement(Target, { className: 'foo' });

var target = 'a';
var b = React.createElement('target', { className: 'foo' });
```

through Babel.

So if you want to use JSX, you have to use `Target` over `target`.

**Comment by Axolot1** [comment]
Thanks so mush, it work now. And i think it's better to keep the code style in JSX in the book, so it won't confuse some beginners.

**Comment by bebraw** [comment]
Yeah, this is a great point to add to the book. Thanks for the discussion. 👍
