### ISSUE TITLE
Running webpack config through babel with require hook

### ISSUE THREAD

**Issue by jchaffin** [survivejs/ama#14]
Hi Juho,

I've been using ES6 syntax while following with the 1.4.2 version of SurviveJS - Webpack and I'm trying to remove the `babel` extension by running the config through a require hook with babel-node. Currently, I have a script called `build.js` that looks like this: 
```js
require('babel-register');
require('./webpack.config.js');
```
Then, in my `package.json` I have:
```js
...
"scripts" : {
  "build": "babel-node ./build.js"
},
...
```
Obviously, this doesn't work because I'm not running the webpack command, but my first idea of passing `build.js` to webpack as the config wasn't successful, so I'm not really sure what do from here. Any suggestions?
Thanks for the help.

**Comment by bebraw** [comment]
Why do you want to drop the `babel` extension?

If you use Node 4 or newer (recommended now anyway), note that Node supports a lot of ES6 functionality. ES6 modules are the biggest omission. This means that if you use a subset supported by Node, you can skip Babel altogether.

See [node.green](http://node.green/) to understand better what features your Node version supports.

**Comment by jchaffin** [comment]
I'm using 7.4.0.  It's something I saw moOx did on his project phenomic with this [commit](https://github.com/MoOx/phenomic/commit/de397746d3e89a78cbb64f1f0fcc6c53605aa6f4). 

I have a separate postcss config file that was supposed to autoload plugins but wasn’t really working. The postcss config is in commonJS so I thought that maybe it wasn’t playing nice with ES6 modules in my webpack config.

Also, could you please clarify what the documentation means by webpack 2 supports es6 modules? Is that not in reference to`webpack.config.js` ? Or is that a feature to be added once webpack 2 is the official release?

Thanks again - your book makes configuration enjoyable, so much appreciated.

**Comment by bebraw** [comment]
> I'm using 7.4.0. It's something I saw moOx did on his project phenomic with this commit.

Alright. If you want to go through `babel-register`, then you could use something like [babel-register-cli](https://www.npmjs.com/package/babel-register-cli) and run that before webpack for the same effect. Or wrap webpack in a bootstrap script that invokes it through Node after performing `babel-register`.

> I have a separate postcss config file that was supposed to autoload plugins but wasn’t really working. The postcss config is in commonJS so I thought that maybe it wasn’t playing nice with ES6 modules in my webpack config.

PostCSS configuration is a little problematic and I'm still investigating good ways to do this. The next release of the book will actually skip the separate file entirely.

> Also, could you please clarify what the documentation means by webpack 2 supports es6 modules? Is that not in reference towebpack.config.js ? Or is that a feature to be added once webpack 2 is the official release?

Webpack 2 can process ES6 modules for you. So even if you aren't using Babel, it will pick up the module definition. The gotcha is that it won't transform code so `const` etc. will pass through. This can be problematic on older browsers and as a result you often end up needing Babel or some other transpiler anyway.

**Comment by jchaffin** [comment]
Okay. Thank you for the help, looking forward to the discussion on PostCSS in your next release. Before closing, is this repo an alright way to get in touch with you for thoughts/questions or do you have another preference?

**Comment by bebraw** [comment]
The AMA is good for bigger questions like this. If you have something casual, feel free to [join me at the book chat](https://gitter.im/survivejs/webpack).

PostCSS needs further research. Most importantly I need to understand better how it works with extract-text-webpack-plugin.

Thanks for the question. 👍
