### ISSUE TITLE
Server-side rendering of react components with webpack

### ISSUE THREAD

**Issue by zksailor534** [survivejs/ama#15]
I've been developing a React component using the react-component-boilerplate, and I just tried testing it in a server-side rendering environment and received:
> ReferenceError: window is not defined

It seems to be a problem with webpack or webpack configuration, specifically in the style-loader or css-loader modules.  Is there any acknowledged method to build an isomorphic/universal React component like this?  Does it have to be compiled differently for client-rendering versus server-rendering?

The component I'm referencing is [react-adminlte-dash](https://github.com/zksailor534/react-adminlte-dash), so all the source code is there if there's anything you need to look into.  Thanks in advance.

**Comment by bebraw** [comment]
Hi,

The current version of the boilerplate hasn't been designed server-side rendering in mind. Look into solutions like isomorphic-webpack. Here's [an interview](http://survivejs.com/blog/isomorphic-webpack-interview/).

I intend to include a little example to the webpack book in very near future.

About the error, `ReferenceError: window is not defined` is most likely about `style-loader` as it injects `window` to the code for hot loading.

I hope this helps. Let me know how it goes. 👍

**Comment by bebraw** [comment]
Hi,

I wrote a [chapter on the topic](https://survivejs.com/webpack/output/server-side-rendering/).

I guess it's time to close this one. 👍
