### ISSUE TITLE
How to fix four colums(lane), newbie

### ISSUE THREAD

**Issue by manderen** [survivejs/ama#16]
Hi,
how can i modify the code to show just four lane?

Regards
Mattias

**Comment by bebraw** [comment]
Hi,

Can you push your code to GitHub so I can have a closer look?

**Comment by manderen** [comment]
Hello, thanks for reply,
Being a newbie I hope nothing is broken. The repo should be the final set of your REACT kanban tutorial.
I pushed to https://github.com/manderen/kanban.git <https://github.com/manderen/kanban.git>

The idea is to have four lanes that notes can move in between without any editable.

**Comment by manderen** [comment]
Here is the mockup pdf for the idea. Really thankful for advice)

**Comment by bebraw** [comment]
Hi,

I missed the pdf. You can upload images here, though.

About fixing to four lanes, the right place to do that would be `LaneStore`. You could add a check against `this.lanes.length` at `create` and skip the logic if there are more than four.

**Comment by manderen** [comment]
Is it possible that you could send a snap of that, I believe it is this part you mention.

 create(lane) {
// If `notes` aren't provided for some reason, // default to an empty array.
lane.notes = lane.notes || [];
this.setState({
lanes: this.lanes.concat(lane)
}); }

**Comment by bebraw** [comment]
You would need a check like this:

```javascript
 create(lane) {
  // If `notes` aren't provided for some reason, // default to an empty array.
  lane.notes = lane.notes || [];

  if (this.lanes.length >= 4) {
    return;
  }

  this.setState({
    lanes: this.lanes.concat(lane)
  });
}
```

So if there are enough lanes already, do nothing.

**Comment by manderen** [comment]
Aha, thanks!
