### ISSUE TITLE
Error: You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by karen-hartley** [survivejs/ama#18]
I am going through your SurviveJS - React book (2018-03-13 version), and just got to the changes to App.jsx on page 79.  When I save and compile, I get a long list of errors starting with 
`ERROR in ./libs/connect.js
Module parse failed: /Users/khartley/kanban-app/libs/connect.js Unexpected token (7:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (7:0)
    at Parser.pp$4.raise (/Users/khartley/kanban-app/node_modules/acorn/dist/acorn.js:2221:15)`

I'm not sure what is needed to fix the error - everything is up to date and just installed this week on my system.  Do you recognize this error?

Thank you for any help you can provide.
Best regards,
Karen Hartley

**Comment by bebraw** [comment]
Hi,

That sounds like a syntax error. I have the code per chapter at https://github.com/survivejs/react-book/tree/dev/project_source .

Could you upload your project to GitHub so I can have a closer look?
