### ISSUE TITLE
Webpack dev-server not updating changes

### ISSUE THREAD

**Issue by RayBowman2017b** [survivejs/ama#19]
HI!

I'm a noob learning Webpack, React, Redux, and Babel.

I've got a problem with webpack dev-server. It doesn't render my updates in watch mode.

It compiles when I save changes to the file, and the page refreshes, but the changes are not reflected on the webpage.

I'm using Loadable to split my code, and I don't really know how to configure webpack dev-server to account for that.

Webpack dev-server was working fine before I did that.

I've pushed my code to there:
https://github.com/RayBowman2017b/react-course-2-Budget-app_03b

If you have any ideas as to what I need to do to get this straightened out, I'd appreciate any advice.

THANKS!

**Comment by bebraw** [comment]
Instead of using watch mode, which will **only** recompile the files, you could try to use Hot Module Replacement and [react-hot-loader](https://www.npmjs.com/package/react-hot-loader). The basic ideas are covered in the book (WDS chapter and HMR appendix)

**Comment by RayBowman2017b** [comment]
As it turns out, all I had to do was to give the "hot" flag on the command:

package,json
    "dev-server": "webpack-dev-server  --env=development --hot",

**Comment by bebraw** [comment]
Ok, cool.
