### ISSUE TITLE
Why did this link rot?

### ISSUE THREAD

**Issue by ghost** [survivejs/ama#20]
http://survivejs.com/common_problems/pyramid.html

Better question. Where did it go?

**Comment by bebraw** [comment]
Hi,

The original is here, https://github.com/survivejs/js_tricks_and_tips/blob/master/common_problems/pyramid.md .

I should rewrite the article and fix the link. Thanks for bringing this up. I'll close this issue when that's done.

**Comment by bebraw** [comment]
Solved.
