### ISSUE TITLE
npm install fails at https://survivejs.com/react/getting-started/setting-up-the-project/

### ISSUE THREAD

**Issue by glebec-v** [survivejs/ama#21]
Hi. I'm trying to create project by your instructions and it looks like quite old project. Would you provide correct certificate or renew somehow it on the server. 
Or may be better to install initial project by `create-react-app`?
![2019-01-30_18-47-15](https://user-images.githubusercontent.com/11569972/51994072-191b0500-24c1-11e9-93a3-507e94fe289c.png)

**Comment by bebraw** [comment]
Hi,

CRA should work as a starting point. The cert errors may be related to
connectivity, though.

Which version of npm/Node are you using?

**Comment by glebec-v** [comment]
Yea, now we often have some connectivity issues, thanks to our regulators )))
... anyway, node -v = 10.15.0, npm -v = 6.4.1

**Comment by bebraw** [comment]
Ok, please try CRA. It should be possible to build the project on top of
that.

**Comment by glebec-v** [comment]
Ok, thanks for your support. Already done CRA )
