### ISSUE TITLE
JSter.net looks gone?

### ISSUE THREAD

**Issue by Stolzenhain** [survivejs/ama#24]
Dear @bebraw  – thanks for many editions of the JSter newsletter – it has always been a great resource (more varied than JS Weekly, IMO)!

Having been a subscriber via the RSS bridge, I only now realized that the whole site is down. 
After some digging, it looks like [176 was the last edition](https://twitter.com/jsterlibs/status/1477942861018677250).

I imagine it is quite some work to maintain this over the years – tell us if you need help setting up an archive or the like.

Best and thanks again for your work!

**Comment by bebraw** [comment]
Thanks for the heads up and for your kind words.

I've been working on a new version of the site during the past months. I think I'll do some quick fixes on that and deploy (I have the domain). Then it will take a bit of iteration to add some missing bits (readme rendering etc.). The whole stack is new and it has been written with the use case in mind.

Most likely the original site went down due to the situation in Ukraine since that's where the server is (or was).

I'll close this issue once the new site is up.

**Comment by Stolzenhain** [comment]
wow, cool! Take your time, that's good to hear.

**Comment by bebraw** [comment]
The site is up at https://jster.net/ .

Note that there are some rough corners still and I think the blog posts will be missing some images. I also didn't restore all the functionality.

If you notice anything particular or miss a specific feature, please open issues at https://github.com/jsterlibs/website-v2/issues .

Thanks again for the report!

**Comment by Stolzenhain** [comment]
Very nice, thanks!

**Comment by Stolzenhain** [comment]
Spent way too long hacking together a little scraper grepping the blog each 24h and returning it as an XML feed so you can subscribe via RSS again:

https://rss.mdl.st/?url=https://jster.net/blog/

Couldn't find any more date info than the `name="built"` tag though.

**Comment by bebraw** [comment]
Ah, I can add RSS easily. Thanks for the heads up. 👍

**Comment by bebraw** [comment]
@Stolzenhain Here we go: https://jster.net/atom.xml .

It showed up in Newsblur at least. I think it can still be improved with descriptions etc.

Here's the technical bit if you are curious: https://github.com/jsterlibs/website-v2/blob/main/site/routes.json#L132, https://github.com/jsterlibs/website-v2/blob/main/site/layouts/rssPage.json .

**Comment by Stolzenhain** [comment]
> I think it can still be improved with descriptions etc.

cool, thanks, I'll have a look + can confirm it working. Guess the Atom template needs some tag tweaking as outlined here:
https://kevincox.ca/2022/05/06/rss-feed-best-practices/

**Comment by bebraw** [comment]
Thanks, I'll have a look.

I think I can shape the `Content-Type` at an edge worker if needed and I'll check the fields in detail at least.

**Comment by bebraw** [comment]
I changed https://jster.net/atom.xml to use Atom format. It doesn't use the right `Content-Type` yet but I'll tackle that later.
