### ISSUE TITLE
Bug - Link for the Webpack book is broken

### ISSUE THREAD

**Issue by ChenxiangWang** [survivejs/ama#25]
Hi,
When I read the book - Webpack, I found some of the links are broken. 
One example is: https://survivejs.com/books/webpack/loading/loading/images 
It happens when I finish a chapter and click on the button for "next chapter".

**Comment by bebraw** [comment]
Thanks, I'll have a look and fix!

**Comment by bebraw** [comment]
Fixed. Thanks a lot!
