### ISSUE TITLE
Re-implementing Kanban app in Redux / TypeScript

### ISSUE THREAD

**Issue by pawelngei** [survivejs/ama#6]
After reading your whole book I'm mostly confused about various Flux implementations. Could you please write a chapter or two re-implementing the Kanban app with Redux or something different?

Also a TypeScript rewrite (instead of just Flow) would be useful, especially showcasing differences between ES6.

I'm going to try these two (separately or together) in a few days, but you have much more experience than me.

**Comment by bebraw** [comment]
> After reading your whole book I'm mostly confused about various Flux implementations. Could you please write a chapter or two re-implementing the Kanban app with Redux or something different?

There's a [Redux implementation](https://github.com/survivejs/redux-demo). After I get 2.0 out, the plan is to focus on porting the content from Alt to Redux (premium material).

See also [Mobservable](https://github.com/survivejs/mobservable-demo) and [Cerebral](https://github.com/survivejs/cerebral-demo) versions. Latter is waiting for a new version of Cerebral. The implementations provide good comparison points.

> Also a TypeScript rewrite (instead of just Flow) would be useful, especially showcasing differences between ES6.

I cannot promise a TypeScript version anytime soon. It has matured a lot, though, and it would likely be feasible to pull it off now. I remember looking into this a few months ago, but there was always some little thing preventing proper progress on this. That said, it should be easier to achieve now.

If you do a TypeScript version, let me know. Even a partial one could be cool and I don't mind collaborating on the tougher parts. :+1:

**Comment by bebraw** [comment]
Just to continue on the topic of Flux, [Redux](http://redux.js.org/) pretty much took the core ideas and condensed them into a simple form. I believe this is one of the key reasons why it became so popular. In short, it ended the "Flux wars".

This doesn't mean we aren't going to see any innovation on the scene. On the contrary. A lot of packages have emerged around Redux itself. And there are alternative lines of thought as linked in my previous reply.
