### ISSUE TITLE
Trouble creating actions and stores for the kaban tutorial

### ISSUE THREAD

**Issue by khieu** [survivejs/ama#7]
Hello Juho,

I am following the webpack & react tutorial on survivejs and so far it's been very helpful. Currently I am stuck at the lesson "React and Flux" at http://survivejs.com/webpack_react/react_and_flux/.  

More specifically, after creating the Alt, NoteActions and NoteStores and gluing them in the App Component, all the actions (including add, delete, update) no longer work. I have followed the steps on that chapter but i could not figure out why. I wonder if you can take a look and help me figure out ?

the github repo is: https://github.com/khieu/kaban_app

Thank you so much for your help, I really appreciate it!.

**Comment by bebraw** [comment]
The problem is that your code doesn't connect `NoteStore.listen` and `NoteStore.unlisten` correctly. This happens because there are two slight typos at your code.

Instead of `ComponentDidMount` and `ComponentWillUnmount` you'll want to use `componentDidMount` and `componentWillUnmount`.
