### ISSUE TITLE
Exclude `style.e5eae09a78b3efd50e73.js` via HtmlWebpackPlugin

### ISSUE THREAD

**Issue by stefanfrede** [survivejs/ama#8]
> If you look closely, you can see a file named style.e5eae09a78b3efd50e73.js in the output. Yours might be different. It is a file generated by Webpack and it looks like this:
> 
> `webpackJsonp([1,3],[function(n,c){}]);`
> 
> Technically it's redundant. It would be safe to exclude the file through a check at HtmlWebpackPlugin template.

Hi!

I tried to exclude it via HtmlWebpackPlugins `excludeChunks` option, but then it was excluded completely.

Is there a way to just exclude the `style.js` without excluding the `style.css`?

Thanks!

Best,
Stefan

**Comment by bebraw** [comment]
As far as I understand, nope. It's a feature of webpack. I actually [opened an issue](https://github.com/webpack/webpack/issues/1967) about this. If webpack could detect empty output, then it wouldn't have to output these files at all.

One way to "solve" it would be to write something to remove these files (a plugin even?). Ideally webpack core would take care of this, though.

Thanks for asking!

**Comment by MtDalPizzol** [comment]
Is there any progress on this? What if `excludeChunks` were based on a RegExp array?

**Comment by bebraw** [comment]
@MtDalPizzol That's an interesting idea. Maybe it would be possible to derive the rule based on the entry name in a smart way. Still a little hacky but better than nothing.

**Comment by MtDalPizzol** [comment]
After digging the plugin's code, I found that we can't exclude the chunk, because it contains the `.js` and the `.css`. What we need is to filter the content of the chunk to exclude the undesired files. But after that, the problem is that it ends up adding a `<script>` tag at the end of the `.html` file with the `src` attribute pointing to the `styles.css` file. I couldn't solve this. =/

**Comment by bebraw** [comment]
https://github.com/Velenir/html-webpack-template-pug has `css-only` option. See https://github.com/webpack/webpack/issues/1967#issuecomment-261049378 . Maybe that's the key.
